# Generated by Django 2.0.6 on 2018-07-08 06:58

from django.db import migrations, models
import users.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True, validators=[users.validators.EmailValidator()])),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
