image: python:3.6

services:
 - postgres
 - docker:dind
 - redis:latest

stages:
 - test
 - release
 - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  DB_NAME: postgres
  DB_USER: postgres
  DB_HOST: postgres
  DB_PASS: postgres
  DB_PORT: 5432
  DEBUG: "True"
  REDIS_URL: "redis://redis:6379"

cache:
  paths:
    - .cache/
    - venv/

before_script:
  - python -m pip install --upgrade pip==9.0.3
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip==9.0.3
  - cd backend
  - python install.py

python_linter:
  stage: test
  script:
    - invoke run-python-linter
  allow_failure: true # for now

python_tests:
  stage: test
  script:
    # Test for missing migrations
    - src/manage.py makemigrations --check --dry-run || (echo "Missing migrations"; false)
    - invoke migrate
    - invoke foundation
    - invoke fixtures
    - invoke run-python-tests --coverage
  allow_failure: true # for now

## TODO frontend linter/tests?

release_develop:
  image: docker:stable
  stage: release
  cache: {}
  before_script:
    - docker login -u saltman -p $CI_PASS $CI_REGISTRY
  script:
    - scripts/build.sh registry.pinigseu.xyz/jumpcut/jumpcut:nginx
    - docker push registry.pinigseu.xyz/saltman/jumpcut:nginx
  only:
    - master
    - nginx # testing this

deploy-develop:
  stage: deploy
  cache: {}
  before_script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key
    - chmod 700 key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i key "$SSH_DESTINATION"
  only:
    - master
