image: python:3.6
services:
 - postgres
 - docker:dind
 - redis:latest
stages:
 - test_python
 - test_react
 - review
 - release
 - deploy
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  CONTAINER_COMMIT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  ALLOWED_HOSTS: "*"
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
  DEBUG: "True"
  PRODUCTION: "False"
  REDIS_URL: "redis://redis:6379"
  SECRET_KEY: "jumpcut"
  TESTING_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
  TESTING_WSGI_APPLICATION: "jumpcut.www_wsgi.application"
  when: manual
cache:
  paths:
    - .cache/
    - venv/
before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - cd backend
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
python_linter:
  stage: test_python
  script:
    - invoke run-python-linter
  allow_failure: true
  when: manual
python_tests:
  stage: test_python
  script:
    # Test for missing migrations
    - src/manage.py makemigrations --check --dry-run || (echo "Missing migrations"; false)
    - invoke migrate
    - invoke foundation
    - invoke fixtures
    - invoke run-python-tests --coverage
  allow_failure: true
test_react:
  image: node:latest
  stage: test_react
  before_script:
    - cd frontend
    - yarn
  cache:
    paths:
    - node_modules/
  script:
     - yarn run test
  when: manual
review:
  stage: review
  before_script:
    - echo "$SSH_REVIEW_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_REVIEW_PRIVATE_KEY" | tr -d '\r' > key
    - chmod 700 key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "$SSH_REVIEW_DESTINATION"
    - ssh -i key "$SSH_REVIEW_DESTINATION"
    - rsync -av ./ --delete /code/$CI_BUILD_REF_SLUG
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_BUILD_REF_SLUG.$REVIEW_APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - review
    - review-app
    - dev
stop_review:
  stage: review
  before_script:
    - echo "Removing Review Directory"
  script:
    - rm -rf /code/$CI_BUILD_REF_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - review
    - review-app
    - dev
release_develop:
  image: tmaier/docker-compose:latest
  variables:
    DOCKER_DRIVER: overlay2
    FRONTEND_DIR: /builds/jumpcut/jumpcut/frontend
    BACKEND_DIR: /builds/jumpcut/jumpcut/backend
    PROD_DOCKER_FILE: production/Dockerfile
    CONTAINER_COMMIT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    ALLOWED_HOSTS: "*"
    DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    DEBUG: "True"
    PRODUCTION: "False"
    REDIS_URL: "redis://redis:6379"
    SECRET_KEY: "jumpcut"
    TESTING_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    TESTING_WSGI_APPLICATION: "jumpcut.www_wsgi.application"

  stage: release
  cache: {}
  before_script:
      - docker-compose --version
      - docker version
      - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - echo "$CONTAINER_COMMIT_IMAGE"
    - cd $FRONTEND_DIR
    - cp .env.template .env
    - docker build --pull -t $CONTAINER_COMMIT_IMAGE -f $PROD_DOCKER_FILE .
    - cd $BACKEND_DIR
    - cp .env.template .env
    - docker build --pull -t $CONTAINER_COMMIT_IMAGE -f $PROD_DOCKER_FILE .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CONTAINER_COMMIT_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  tags:
    - latest
    - master
    - release
  only:
    - master
deploy-develop:
  stage: deploy
  cache: {}
  before_script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key
    - chmod 700 key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i key "$SSH_DESTINATION"
  only:
    - master
