dist: trusty
sudo: required
language: python
cache: pip
services:
  - postgresql
  - redis-server
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
python:
    - 3.6.5
env:
  global:
      - DOCKER_DRIVER=overlay2
      - DJANGO=2.0.8
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - PRODUCTION=False
      - REDIS_URL=redis://localhost:6379
      - SECRET_KEY=jumpcut
      - DATABASE_URL=postgres://postgres:postgres@localhost:5433/travis
      - TESTING_DATABASE_URL=postgres://postgres:postgres@localhost:5433/travis_ci
      - WSGI_APPLICATION=jumpcut.www_wsgi.application
      - PGPORT=5433
before_install:
   - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
   - sudo service postgresql restart
   - sleep 1
install:
   - pip install -r ./backend/requirements.txt
   - pip install -r ./backend/testing_requirements.txt
   - pip install codecov
before_script:
   - psql -c 'create database travis_ci;' -U postgres
script:
   - cd backend
   - invoke run-python-linter
   - src/manage.py migrate  
   - invoke foundation
   - invoke fixtures
   - invoke run-python-tests --coverage
after_success:
   - codecov --token=$CODECOV_TOKEN
   - docker login -u $DOCKER_USER -p $DOCKER_PASS
   - export REPO=streisandjumpcut/streisand
   - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
   - docker build -f ../frontend/production/Dockerfile -t $REPO:$COMMIT .
   - docker build -f ./production/Dockerfile -t $REPO:$COMMIT .
   - docker tag $REPO:$COMMIT $REPO:$TAG
   - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
   - docker push $REPO
