dist: trusty
sudo: required
language: python
cache: pip
services:
  - postgresql
  - redis
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
python:
    - 3.6.5
env:
  global:
      - DOCKER_DRIVER=overlay2
      - DJANGO=2.0.8
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@localhost:5433/postgres
      - DEBUG=True
      - PRODUCTION=False
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=jumpcut
      - TESTING_DATABASE_URL=postgres://postgres:postgres@localhost:5433/postgres
      - TESTING_WSGI_APPLICATION=jumpcut.www_wsgi.application
      - PGPORT=5433
before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
install:
    - pip install -r ./backend/requirements.txt
    - pip install -r ./backend/testing_requirements.txt
    - pip install codecov
script:
  - cp backend/.env.template.travis backend/.env
  - cd backend
  - flake8 src
  - src/manage.py makemigrations
  - src/manage.py migrate
  - coverage run src/manage.py test backend/src
  - coverage report --include=src/*.*

after_success:
    - coverage report --include=src/*.*
    - codecov --token=$CODECOV_TOKEN
 
