version: '3'

services:

    postgres:
        restart: always
        image: postgres:latest
        env_file: env
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: redis:latest
    api:
        command: python src/manage.py runserver_plus 0.0.0.0:8000
        build: backend
        volumes:
            - ./backend:/code
        depends_on:
            - postgres
            - redis
        env_file: env
        environment:
            DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
        ports:
            - "8000:8000"
    tracker:
        command: python src/manage.py runserver_plus 0.0.0.0:7070
        build: backend
        volumes:
            - ./backend:/code
        depends_on:
            - postgres
            - redis
        env_file: env
        environment:
            DJANGO_SETTINGS_MODULE: jumpcut.settings.tracker_settings
        ports:
            - "7070:7070"
    frontend:
        build: frontend
        ports:
            - "8001:3000"
        volumes:
            - ./frontend/src:/code/src
volumes:
    pgdata:
