# Docker compose for the dev server
#
version: '3'

services:
    postgres:
        container_name: db
        restart: always
        image: postgres:latest
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        container_name: redis
        image: redis:latest
        restart: always
    www:
            container_name: www
            build:
                context: ./backend
                dockerfile: Dockerfile-production
            depends_on:
                - postgres
                - redis
            env_file: .env
            volumes:
              - "./backend/src:/code/src"
              - "./backend/src/static:/code/src/static"
            ports:
                - "8000:8000"
                - "7070:7070"
            restart: always
    nginx:
            container_name: nginx
            build:
                context: ./nginx
                dockerfile: Dockerfile
            depends_on:
                - www
            volumes:
                - "static:/code/dist"
                - "static:/code/src/static/"
            ports:
                - "80:80"
                - "443:443"
volumes:
    pgdata:
    static:

