# Docker compose for the dev server
#
version: '3'

services:
  api:
    image: gitlab.pinigseu.xyz:4567/jumpcut/jumpcut:latest
    build:
      context: ./backend
      dockerfile: ./production/Dockerfile
    container_name: api
    depends_on:
    - postgres
    - redis
    env_file: ./backend/.env
    ports:
    - 7070:7070
    - 8000:8000
    restart: always
    volumes:
    - ./backend/src:/code/src/
  nginx_react:
    build:
      context: ./frontend
      dockerfile: ./production/Dockerfile
    container_name: nginx_react
    depends_on:
    - api
    env_file: ./frontend/.env
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./backend/src:/usr/share/nginx/src/
  celery:
      image: gitlab.pinigseu.xyz:4567/jumpcut/jumpcut:latest
      build:
        context: ./backend
        dockerfile: ./production/Dockerfile
      command: bash -c "celery worker --workdir /code/src -A jumpcut -l info"
      environment:
        PYTHONPATH: /code/src
        C_FORCE_ROOT: "true"
        DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
      env_file: ./backend/.env
      container_name: celery
      volumes:
      - ./backend/src:/code/src
      depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    container_name: db
    volumes:
    - pgdata:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    env_file: ./backend/.env
    restart: always
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
volumes:
  pgdata:
  