# Docker compose for the dev server
#
version: '3'

services:
  api:
    image: registry.pinigseu.xyz/jumpcut/jumpcut:latest
    container_name: api
    volumes:
    - ./backend/src:/code/src/
    build:
      context: ./backend
      dockerfile: ./production/Dockerfile
    ports:
    - 7070:7070
    - 8000:8000
    env_file: ./backend/.env
    depends_on:
    - postgres
    - redis
    - nginx_react
    restart: always
  celerybeat:
    image: registry.pinigseu.xyz/jumpcut/jumpcut:latest
    command: bash -c "celery beat --workdir /code/src -A jumpcut -l info"
    container_name: celerybeat
    volumes:
    - ./backend/src:/code/src
    env_file: ./backend/.env
    environment:
      C_FORCE_ROOT: 'true'
      DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
      PYTHONPATH: /code/src
    depends_on:
    - celeryworker
    - postgres
    - redis
  celeryworker:
    image: registry.pinigseu.xyz/jumpcut/jumpcut:latest
    command: bash -c "celery worker --workdir /code/src -A jumpcut -l info"
    container_name: celeryworker
    volumes:
    - ./backend/src:/code/src
    env_file: ./backend/.env
    environment:
      C_FORCE_ROOT: 'true'
      DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
      PYTHONPATH: /code/src
    depends_on:
    - api
    - postgres
    - redis
  nginx_react:
    build:
      context: ./frontend
      dockerfile: ./production/Dockerfile
    container_name: nginx_react
    env_file: ./frontend/.env
    ports:
    - 443:443
    - 80:80
    restart: always
    volumes:
    - ./backend/src:/usr/share/nginx/src/
  postgres:
    image: postgres:alpine
    container_name: db
    volumes:
    - pgdata:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    env_file: ./backend/.env
    restart: always
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
volumes:
  pgdata:
