version: '3'

services:

  api:
    build: backend
    container_name: api_dev
    command: python src/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
    - postgres
    - redis
    env_file: ./.env
    environment:
      DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
    ports:
    - 8000:8000
    volumes:
    - ./backend:/code
  frontend:
    build: frontend
    container_name: frontend
    command: npm run dev
    env_file: ./frontend/.env
    ports:
    - 8001:3000
    volumes:
    - ./frontend/src:/react/src
  postgres:
    image: postgres:alpine
    container_name: db_dev
    volumes:
    - pgdata:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    env_file: ./.env
    restart: always
  redis:
    image: redis:alpine
    container_name: redis_dev
  tracker:
    build:
      context: ./backend
    container_name: tracker_dev
    command: python src/manage.py runserver_plus 0.0.0.0:7070
    depends_on:
    - postgres
    - redis
    env_file: ./.env
    environment:
      DJANGO_SETTINGS_MODULE: jumpcut.settings.tracker_settings
    ports:
    - 7070:7070
    volumes:
    - ./backend:/code
volumes:
  pgdata:
