version: '3'

services:

  api:
    build: backend
    command: python src/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
    - postgres
    - redis
    env_file: docker_env
    environment:
      DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
    ports:
    - 8000:8000
    volumes:
    - ./backend/src/static:/static
    - ./backend:/code
  frontend:
    build: frontend
    ports:
    - 8001:3000
    volumes:
    - ./frontend/dist:/code/dist
    - ./frontend/src:/code/src
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
    - api
    - frontend
    ports:
    - 443:443
    - 80:80
    volumes:
    - ./backend/src/static:/static
    - ./frontend/dist:/static
    - ./logs/nginx:/tmp/logs
  postgres:
    image: postgres:latest
    volumes:
    - pgdata:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    env_file: docker_env
    restart: always
  redis:
    image: redis:latest

  tracker:
    build: backend
    command: python src/manage.py runserver_plus 0.0.0.0:7070
    depends_on:
    - postgres
    - redis
    env_file: docker_env
    environment:
      DJANGO_SETTINGS_MODULE: jumpcut.settings.tracker_settings
    ports:
    - 7070:7070
    volumes:
    - ./backend:/code
volumes:
  pgdata:
