version: '3'

services:

  api:
    build: backend
    command: python src/manage.py runserver_plus [::]:8000
    container_name: api_dev
    depends_on:
    - postgres
    - redis
    env_file: ./.env
    environment:
      DJANGO_SETTINGS_MODULE: jumpcut.settings.www_settings
    networks:
    - jumpcut
    ports:
    - 8000:8000
    volumes:
    - ./backend:/code
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    container_name: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - jumpcut
    environment:
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    - bootstrap.memory_lock=true
    - cluster.name=docker-cluster
    hostname: elasticsearch
    depends_on:
    - api
    - postgres
    ulimits:
      memlock:
        hard: -1
        soft: -1
  frontend:
    build: frontend
    command: yarn run dev
    container_name: frontend
    depends_on:
    - api
    env_file: ./frontend/.env
    networks:
    - jumpcut
    ports:
    - 8001:3000
    volumes:
    - ./frontend/src:/react/src
  postgres:
    image: postgres:alpine
    container_name: db_dev
    volumes:
    - pgdata:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    networks:
    - jumpcut
    env_file: ./.env
    restart: always
  redis:
    image: redis:alpine
    container_name: redis_dev
    ports:
    - 6379:6379
    networks:
    - jumpcut
  tracker:
    build:
      context: ./backend
    command: python src/manage.py runserver_plus 0.0.0.0:7070
    container_name: tracker_dev
    depends_on:
    - api
    - postgres
    - redis
    env_file: ./.env
    environment:
      DJANGO_SETTINGS_MODULE: jumpcut.settings.tracker_settings
    networks:
    - jumpcut
    ports:
    - 7070:7070
    volumes:
    - ./backend:/code
volumes:
  esdata:
  pgdata:

networks:
  jumpcut:
