apiVersion: v1
data:
  APIURL: https://localhost:8000
  NODE_ENV: development
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-frontend--env
  name: frontend-frontend--env
