apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - args:
        - yarn
        - run
        - dev
        env:
        - name: APIURL
          valueFrom:
            configMapKeyRef:
              key: APIURL
              name: frontend-frontend--env
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: frontend-frontend--env
        image: frontend
        name: frontend
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /react/src
          name: frontend-claim0
      restartPolicy: Always
      volumes:
      - name: frontend-claim0
        persistentVolumeClaim:
          claimName: frontend-claim0
status: {}
