apiVersion: v1
data:
  ALLOWED_HOSTS: '*'
  BANDIT_EMAIL: ""
  CORS_ORIGIN_ALLOW_ALL: "True"
  CORS_URL_REGEX: ""
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  DEBUG: "True"
  DEFAULT_FROM_EMAIL: ""
  DEFAULT_REPLY_TO_EMAIL: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  HOST: localhost
  HOST_IP: 192.168.2.156
  MYSQL_HOST: ""
  MYSQL_PORT: ""
  MYSQL_PWD: ""
  MYSQL_USER: ""
  MYSQLDB_NAME: ""
  OLD_SITE_HASH: ""
  PRODUCTION: "False"
  REDIS_URL: redis://redis:6379
  RT_API_KEY: ""
  SECRET_KEY: changeme
  SITE_NAME: jumpcut
  SITE_URL: http://localhost:8000/
  TEST_RUNNER: jumpcut.tests.CustomTestSuiteRunner
  TESTING_DB_HOST: postgres
  TESTING_DB_NAME: ci
  TESTING_DB_PASS: postgres
  TESTING_DB_PORT: "5432"
  TESTING_DB_SERVICE: postgres
  TESTING_DB_USER: postgres
  TESTING_WSGI_APPLICATION: jumpcut.www_wsgi.application
  TRACKER_URL: http://localhost:7070/
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-env
  name: postgres-env
