apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --file docker-compose.production.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-react
  name: nginx-react
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: nginx-react
status:
  loadBalancer: {}
