# Generated by Django 2.0.4 on 2018-05-06 04:51

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediainfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file_path', models.CharField(editable=False, max_length=1024)),
                ('file_size', models.CharField(editable=False, max_length=16)),
                ('runtime', models.DurationField(editable=False, null=True)),
                ('resolution_width', models.SmallIntegerField(editable=False, null=True)),
                ('resolution_height', models.SmallIntegerField(editable=False, null=True)),
                ('display_aspect_ratio', models.CharField(max_length=16)),
                ('bit_rate', models.CharField(max_length=16)),
                ('frame_rate', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('has_chapters', models.BooleanField()),
                ('is_dxva_compliant', models.BooleanField()),
                ('is_quality_encode', models.BooleanField()),
                ('audio', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('subtitles', picklefield.fields.PickledObjectField(default=[], editable=False)),
            ],
        ),
    ]
