# Generated by Django 2.0.6 on 2018-06-19 09:07

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        CITextExtension,
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. ASCII letters, digits, and ./-/_ characters only.', max_length=50, unique=True, validators=[users.validators.UsernameValidator()]),
        ),
    ]
