# Generated by Django 2.0.6 on 2018-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180619_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userannounce',
            options={'get_latest_by': 'time_stamp', 'ordering': ['-time_stamp']},
        ),
        migrations.AlterField(
            model_name='userclass',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
