# Generated by Django 2.0.6 on 2018-07-03 08:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180628_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userannounce',
            name='total_bytes_downloaded',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userannounce',
            name='total_bytes_uploaded',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userannounce',
            name='suspicious_behaviors',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
