# Generated by Django 2.0.6 on 2018-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180703_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannounce',
            name='peer_id',
            field=models.CharField(max_length=60),
        ),
    ]
