# Generated by Django 2.0.4 on 2018-05-06 04:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('first_snatched', models.DateTimeField(null=True)),
                ('last_snatched', models.DateTimeField(db_index=True, null=True)),
                ('snatch_count', models.IntegerField(db_index=True, default=0)),
                ('last_seeded', models.DateTimeField(null=True)),
                ('seed_time', models.DurationField(default=datetime.timedelta(0))),
                ('hnr_countdown_started_at', models.DateTimeField(null=True)),
                ('is_hit_and_run', models.NullBooleanField()),
            ],
        ),
    ]
