# Generated by Django 2.0.4 on 2018-05-06 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torrent_stats', '0002_torrentstats_torrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrent_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='torrentstats',
            unique_together={('user', 'torrent')},
        ),
        migrations.AlterIndexTogether(
            name='torrentstats',
            index_together={('user', 'torrent')},
        ),
    ]
