# Generated by Django 2.0.6 on 2018-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent_stats', '0003_auto_20180708_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentstats',
            name='hnr_countdown_started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='torrentstats',
            name='is_hit_and_run',
            field=models.NullBooleanField(default=None),
        ),
    ]
