# Docker compose for the dev server
#
version: '3'

services:
    db:
        image: postgres:latest
        env_file: env
        volumes:
            - dbdata:/var/lib/postgresql/data
        restart: always
    redis:
        image: redis:latest
        restart: always
    www:
        image: registry.ronzertnert.me/jumpcut/jumpcut:latest
        env_file: env
        depends_on:
            - db
            - redis
        env_file: env
        ports:
            - "8000:8000"
            - "7070:7070"
        restart: always
    celery:
        image: registry.ronzertnert.me/jumpcut/jumpcut:latest
        command: celery worker --workdir /code/src -A jumpcut -l info
        depends_on:
            - db
            - redis
        env_file: env
        environment:
            - C_FORCE_ROOT=true
        restart: always
volumes:
    dbdata:
