# Docker compose for the dev server
#
version: '3'

services:
    postgres:
        restart: always
        image: postgres:latest
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: redis:latest
        restart: always
    redis:
        image: redis:latest
        restart: always
    www:
        image: registry.pinigseu.xyz/jumpcut/jumpcut:master
        depends_on:
            - postgres
            - redis
        env_file: .env
        ports:
            - "8000:8000"
            - "7070:7070"
        restart: always
    celery:
        image: registry.pinigseu.xyz/jumpcut/jumpcut:master
        command: celery worker --workdir /code/src -A jumpcut -l info
        depends_on:
            - postgres
            - redis
        env_file: .env
        environment:
            - C_FORCE_ROOT=true
        restart: always
    nginx:
            build:
                context: ../
                dockerfile: ./nginx/Dockerfile
            depends_on:
                - www
            volumes:
                - "./backend/src/static:/static"
                - "./frontend/dist:/static"
                - "./logs/nginx:/tmp/logs"
            ports:
                - "80:80"
                - "443:443"
volumes:
    pgdata:
