# Docker compose for the dev server
#
version: '3'

services:
    postgres:
        restart: always
        image: postgres:latest
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: redis:latest
        restart: always
    redis:
        image: redis:latest
        restart: always
    www:
        image: registry.ronzertnert.me/jumpcut/jumpcut:master
        depends_on:
            - postgres
            - redis
        env_file: .env
        ports:
            - "8000:8000"
            - "7070:7070"
        restart: always
    celery:
        image: registry.ronzertnert.me/jumpcut/jumpcut:master
        command: celery worker --workdir /code/src -A jumpcut -l info
        depends_on:
            - postgres
            - redis
        env_file: .env
        environment:
            - C_FORCE_ROOT=true
        restart: always
volumes:
    pgdata:
