# Generated by Django 2.0.6 on 2018-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='compact_bytes_repr',
        ),
        migrations.AddField(
            model_name='peer',
            name='compact_representation',
            field=models.CharField(default='', help_text='base64 encoded compact representation, sent as bytes to announcing torrent clients', max_length=10),
            preserve_default=False,
        ),
    ]
