# Generated by Django 2.0.6 on 2018-07-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('torrents', '0002_auto_20180708_0658'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='announce_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='users.UserAnnounceKey'),
        ),
        migrations.AddField(
            model_name='peer',
            name='torrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='torrents.TorrentFile'),
        ),
        migrations.AddField(
            model_name='peer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('torrent', 'ip_address', 'port')},
        ),
        migrations.AlterIndexTogether(
            name='peer',
            index_together={('torrent', 'ip_address', 'port')},
        ),
    ]
