# Generated by Django 2.0.6 on 2018-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180626_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='last_announce',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='peer_id',
            field=models.CharField(max_length=60),
        ),
    ]
