# Generated by Django 2.0.4 on 2018-05-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='creator',
        ),
    ]
