# Generated by Django 2.0.5 on 2018-05-21 02:28

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='position',
            field=positions.fields.PositionField(default=-1, editable=False),
        ),
    ]
