# Generated by Django 2.0.4 on 2018-05-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='modified_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
