# Generated by Django 2.0.4 on 2018-05-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_forumtopic_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='modified_count',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='modified_count',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forums.ForumTopic'),
        ),
    ]
