# Generated by Django 2.0.5 on 2018-05-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20180521_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
