# Generated by Django 2.0.4 on 2018-05-06 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_auto_20180506_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.ForumGroup'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='modified_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='modified_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='is_archived',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.ForumTopic'),
        ),
    ]
