# Generated by Django 2.0.4 on 2018-05-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_forumtopic_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
