# Generated by Django 2.0.5 on 2018-05-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20180521_0339'),
        ('forums', '0002_auto_20180521_0228'),
    ]

    operations = [
    ]
