# Generated by Django 2.0.6 on 2018-06-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_formats', '0002_genre'),
        ('films', '0002_auto_20180604_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_tags',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tags',
        ),
        migrations.AddField(
            model_name='film',
            name='genre_tags',
            field=models.ManyToManyField(blank=True, related_name='films', to='media_formats.Genre'),
        ),
    ]
