# Generated by Django 2.0.5 on 2018-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20180510_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='fanart_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
    ]
