# Generated by Django 2.0.6 on 2018-06-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20180612_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='film',
            new_name='films',
        ),
    ]
