# Generated by Django 2.0.6 on 2018-06-04 13:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReseedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TorrentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TorrentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40, unique=True)),
                ('created_by', models.CharField(max_length=128, null=True)),
                ('is_single_file', models.BooleanField()),
                ('file', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('files', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('directory_name', models.CharField(max_length=512, null=True)),
                ('total_size_in_bytes', models.BigIntegerField()),
                ('piece_size_in_bytes', models.BigIntegerField()),
                ('pieces', models.TextField(help_text='base64 encoded binary pieces data')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.NullBooleanField(choices=[(None, 'Not Yet Moderated'), (True, 'Approved'), (False, 'Work In Progress')])),
                ('last_seeded', models.DateTimeField(null=True)),
                ('snatch_count', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('can_upload', 'Can upload new torrents'), ('can_moderate', 'Can moderate torrents'), ('can_request_reseed', 'Can request a reseed')),
            },
        ),
    ]
