# Generated by Django 2.0.4 on 2018-05-10 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torrents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediainfo', '0001_initial'),
        ('films', '0002_auto_20180510_0335'),
        ('tracker', '0001_initial'),
        ('media_formats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='torrentcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torrentcomment',
            name='torrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='torrents.Torrent'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='codec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrents', to='media_formats.Codec'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrents', to='media_formats.Container'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torrent',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrents', to='films.Film'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='mediainfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mediainfo.Mediainfo'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='metainfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='torrent', to='torrents.TorrentMetaInfo'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_torrents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torrent',
            name='reseed_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_torrent', to='torrents.ReseedRequest'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrents', to='media_formats.Resolution'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='source_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrents', to='media_formats.SourceMedia'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='swarm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='torrent', to='tracker.Swarm'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_torrents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reseedrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reseedrequest',
            name='torrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseed_requests', to='torrents.Torrent'),
        ),
    ]
