# Generated by Django 2.0.6 on 2018-06-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_auto_20180604_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrentcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='torrentcomment',
            name='torrent',
        ),
        migrations.DeleteModel(
            name='TorrentComment',
        ),
    ]
