# Generated by Django 2.0.5 on 2018-06-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_auto_20180529_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='torrents', to='releases.Release'),
        ),
    ]
