# Generated by Django 2.0.4 on 2018-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRottenTomatoes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=1024)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('critics_rating', models.PositiveSmallIntegerField(null=True)),
                ('critics_rating_string', models.CharField(max_length=32)),
                ('audience_rating', models.PositiveSmallIntegerField(null=True)),
                ('audience_rating_string', models.CharField(max_length=32)),
                ('runtime_in_minutes', models.PositiveSmallIntegerField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
