# Generated by Django 2.0.4 on 2018-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TorrentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film_title', models.CharField(max_length=1024)),
                ('film_year', models.PositiveSmallIntegerField(null=True)),
                ('description', models.TextField()),
                ('release_name', models.CharField(max_length=255)),
                ('requester_followed_through', models.BooleanField(default=False)),
                ('is_source', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('can_request', 'Can make new torrent requests'),),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty_in_bytes', models.BigIntegerField(default=0)),
            ],
            options={
                'permissions': (('can_vote', 'Can vote on torrent requests'),),
            },
        ),
    ]
