# Generated by Django 2.0.5 on 2018-05-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torrent_requests', '0001_initial'),
        ('torrents', '0001_initial'),
        ('imdb', '0001_initial'),
        ('media_formats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_request_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='torrent_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='torrent_requests.TorrentRequest'),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='codec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_requests', to='media_formats.Codec'),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_requests', to='media_formats.Container'),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='filling_torrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_filled', to='torrents.TorrentFile'),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='imdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imdb.FilmIMDb'),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_requests', to='media_formats.Resolution'),
        ),
        migrations.AddField(
            model_name='torrentrequest',
            name='source_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrent_requests', to='media_formats.SourceMedia'),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='torrent_requests.TorrentRequest'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('author', 'torrent_request')},
        ),
    ]
